
GET http://localhost:3000/serviceordering/api/v1/GetOrderNotExist


###
POST http://localhost:3000/resourceinventory/api/v1/ObtainReservedNumber
Content-Type: application/json

{
    "ICC": "123456789009876"
}


###
GET http://localhost:3000/serviceinventory/api/v1/ActiveServices?MSISDN=33001122


###
POST http://localhost:3000/executecollection/api/v1/ExecuteCollection
Content-Type: application/json

{
  "collectionId": "abc123"
}

